### PR TITLE
Add json config sources before environment variables to prevent gotcha

### PR DESCRIPTION
**Pull request by p-m-j**
Noticed that it was not possible to override configuration via azure configuration as appsettings.json overruled the env vars.

### CODE REVIEW

**Comment by LockTar** [comment]
Can you explain in a bit more detail because appsettings should set the log level. Microsoft is moving in that direction.

**Comment by p-m-j** [comment]
Without this change the IConfiguration sources are in order

1. Environment Variables (added by ConfigureFunctionsWorkerDefaults)
1. CLI Args (added by ConfigureFunctionsWorkerDefaults)
1. appsettings.json

if I add an arbitrary setting to appsettings.json "Foo__Bar__Baz":"Qux" but later wish to customize this per environment / instance via the azure portal (or terraform etc) I cannot as the appsettings.json source overrules the environment variables set in azure Configuration.

With this change the config sources are 

1. appsettings.json
1. Environment Variables (added by ConfigureFunctionsWorkerDefaults)
1. CLI Args (added by ConfigureFunctionsWorkerDefaults)

Which means that values from appsettings.json are only respected until overriden in azure config.

Real world examples of things one might like to override at the infrastructure tier

+ APPLICATIONINSIGHTS_CONNECTION_STRING
+ A database connection string
+ Base address for a web api

**Comment by LockTar** [comment]
Just to confirm. With this change: 
If the app configuration is present in Azure function app "configuration" blade (in example APPLICATIONINSIGHTS_CONNECTION_STRING) that value will be used and will override the value in appsettings.json file. 

I agree this should be the way. I don't use this repo anymore because I'm back to in process version of function app because of all the bugs and missing/buggy features of isolated... Hopefully everything will be fixed around the release with .NET 8.

Maybe we should combine this PR with the [documentation update](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights) for removing the default rule.

```C#
var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .ConfigureServices(services => {
        services.AddApplicationInsightsTelemetryWorkerService();
        services.ConfigureFunctionsApplicationInsights();
    })
    .ConfigureLogging(logging =>
    {
        logging.Services.Configure<LoggerFilterOptions>(options =>
        {
            LoggerFilterRule defaultRule = options.Rules.FirstOrDefault(rule => rule.ProviderName
                == "Microsoft.Extensions.Logging.ApplicationInsights.ApplicationInsightsLoggerProvider");
            if (defaultRule is not null)
            {
                options.Rules.Remove(defaultRule);
            }
        });
    })
    .Build();

host.Run();
```

Because that is different in this repository. That was the next thing I wanted to do but is somewhat related with the PR.

**Comment by p-m-j** [comment]
> If the app configuration is present in Azure function app "configuration" blade (in example APPLICATIONINSIGHTS_CONNECTION_STRING) that value will be used and will override the value in appsettings.json file.

In practice yes, (unless a higher priority configuation provider is registered with a value present for that configuration key)






> Maybe we should combine this PR with the [documentation update](https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide#application-insights) for removing the default rule.

This doesn't seem like something to worry about, the same IServiceCollection is used regardless.

There isn't a gotya with regards to where the logging filter is removed, but breaking the standard conventions for IConfiguration will (or in my case did) lead to mistakes.

**Review by LockTar — APPROVED** [review]

**Comment by LockTar** [comment]
I added extra documentation on how to overwrite the values in Azure

**Pull request merged**
