### PR TITLE
Fix duplicate log entries

### PR DESCRIPTION
**Pull request by p-m-j**
Updating Worker.Sdk fixes duplicate log messages introduced by #3

### CODE REVIEW

**Review by LockTar — APPROVED** [review]

**Comment by LockTar** [comment]
So this is tested? Didn't had time to test everything yet.

**Comment by p-m-j** [comment]
@LockTar - Yes indeed, evidence attached

image

image

**Comment by LockTar** [comment]
@p-m-j thank you for helping. I already updated everything else in the repository and tested everything. I think all the problems are solved right now.
See [this comment](https://github.com/Azure/azure-functions-dotnet-worker/issues/1182#issuecomment-1706459525) for more information.

**Comment by p-m-j** [comment]
@LockTar Not at all, was the least I could do. Your efforts have saved me countless hours of frustration for which I am very grateful.

**Pull request merged**
